# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainDesign.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1057, 432)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(33, 33, 33);\n"
"alternate-background-color: rgb(0, 185, 255);")
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(589, 78))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 2, 1)
        self.settingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingsButton.setMinimumSize(QtCore.QSize(89, 24))
        self.settingsButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.0340909, x2:1, y2:0, stop:0 rgba(255, 255, 255, 0));\n"
"selection-color: rgb(0, 185, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"Open Sans\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/Settings-02.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsButton.setIcon(icon)
        self.settingsButton.setObjectName("settingsButton")
        self.gridLayout_4.addWidget(self.settingsButton, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(228, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 1, 1, 1)
        self.instructionButton = QtWidgets.QPushButton(self.centralwidget)
        self.instructionButton.setMinimumSize(QtCore.QSize(89, 24))
        self.instructionButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.0340909, x2:1, y2:0, stop:0 rgba(255, 255, 255, 0));\n"
"selection-color: rgb(0, 185, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"Open Sans\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/note-2-xxl.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.instructionButton.setIcon(icon1)
        self.instructionButton.setObjectName("instructionButton")
        self.gridLayout_4.addWidget(self.instructionButton, 1, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_5.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(199, 29))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(199, 29))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(199, 29))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(199, 29))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(199, 29))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.pic4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pic4.sizePolicy().hasHeightForWidth())
        self.pic4.setSizePolicy(sizePolicy)
        self.pic4.setMinimumSize(QtCore.QSize(199, 179))
        self.pic4.setText("")
        self.pic4.setScaledContents(False)
        self.pic4.setAlignment(QtCore.Qt.AlignCenter)
        self.pic4.setObjectName("pic4")
        self.gridLayout_3.addWidget(self.pic4, 1, 3, 1, 1)
        self.pic3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pic3.sizePolicy().hasHeightForWidth())
        self.pic3.setSizePolicy(sizePolicy)
        self.pic3.setMinimumSize(QtCore.QSize(199, 179))
        self.pic3.setText("")
        self.pic3.setScaledContents(False)
        self.pic3.setAlignment(QtCore.Qt.AlignCenter)
        self.pic3.setObjectName("pic3")
        self.gridLayout_3.addWidget(self.pic3, 1, 2, 1, 1)
        self.pic2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pic2.sizePolicy().hasHeightForWidth())
        self.pic2.setSizePolicy(sizePolicy)
        self.pic2.setMinimumSize(QtCore.QSize(199, 179))
        self.pic2.setText("")
        self.pic2.setScaledContents(False)
        self.pic2.setAlignment(QtCore.Qt.AlignCenter)
        self.pic2.setObjectName("pic2")
        self.gridLayout_3.addWidget(self.pic2, 1, 1, 1, 1)
        self.pic1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pic1.sizePolicy().hasHeightForWidth())
        self.pic1.setSizePolicy(sizePolicy)
        self.pic1.setMinimumSize(QtCore.QSize(199, 179))
        self.pic1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pic1.setText("")
        self.pic1.setScaledContents(False)
        self.pic1.setAlignment(QtCore.Qt.AlignCenter)
        self.pic1.setWordWrap(False)
        self.pic1.setObjectName("pic1")
        self.gridLayout_3.addWidget(self.pic1, 1, 0, 1, 1)
        self.pic5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pic5.sizePolicy().hasHeightForWidth())
        self.pic5.setSizePolicy(sizePolicy)
        self.pic5.setMinimumSize(QtCore.QSize(199, 179))
        self.pic5.setText("")
        self.pic5.setScaledContents(False)
        self.pic5.setAlignment(QtCore.Qt.AlignCenter)
        self.pic5.setObjectName("pic5")
        self.gridLayout_3.addWidget(self.pic5, 1, 4, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 1, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_5.addItem(spacerItem2, 2, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem3, 1, 6, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 7, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 3, 0, 2, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.button1 = QtWidgets.QLabel(self.centralwidget)
        self.button1.setMinimumSize(QtCore.QSize(0, 45))
        self.button1.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button1.setFont(font)
        self.button1.setStyleSheet("")
        self.button1.setFrameShape(QtWidgets.QFrame.Box)
        self.button1.setAlignment(QtCore.Qt.AlignCenter)
        self.button1.setObjectName("button1")
        self.verticalLayout_6.addWidget(self.button1)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.button2 = QtWidgets.QLabel(self.centralwidget)
        self.button2.setMinimumSize(QtCore.QSize(0, 45))
        self.button2.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button2.setFont(font)
        self.button2.setStyleSheet("")
        self.button2.setFrameShape(QtWidgets.QFrame.Box)
        self.button2.setAlignment(QtCore.Qt.AlignCenter)
        self.button2.setObjectName("button2")
        self.verticalLayout_7.addWidget(self.button2)
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.button3 = QtWidgets.QLabel(self.centralwidget)
        self.button3.setMinimumSize(QtCore.QSize(0, 45))
        self.button3.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button3.setFont(font)
        self.button3.setStyleSheet("")
        self.button3.setFrameShape(QtWidgets.QFrame.Box)
        self.button3.setAlignment(QtCore.Qt.AlignCenter)
        self.button3.setObjectName("button3")
        self.verticalLayout_9.addWidget(self.button3)
        self.gridLayout.addLayout(self.verticalLayout_9, 0, 2, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.button4 = QtWidgets.QLabel(self.centralwidget)
        self.button4.setMinimumSize(QtCore.QSize(0, 45))
        self.button4.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button4.setFont(font)
        self.button4.setStyleSheet("")
        self.button4.setFrameShape(QtWidgets.QFrame.Box)
        self.button4.setAlignment(QtCore.Qt.AlignCenter)
        self.button4.setObjectName("button4")
        self.verticalLayout_10.addWidget(self.button4)
        self.gridLayout.addLayout(self.verticalLayout_10, 0, 3, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.button5 = QtWidgets.QLabel(self.centralwidget)
        self.button5.setMinimumSize(QtCore.QSize(0, 45))
        self.button5.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button5.setFont(font)
        self.button5.setStyleSheet("")
        self.button5.setFrameShape(QtWidgets.QFrame.Box)
        self.button5.setAlignment(QtCore.Qt.AlignCenter)
        self.button5.setObjectName("button5")
        self.verticalLayout_11.addWidget(self.button5)
        self.gridLayout.addLayout(self.verticalLayout_11, 0, 4, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 5, 0, 1, 2)
        self.gridLayout_6.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Speaker Lightboard"))
        self.label.setText(_translate("MainWindow", "Speaker Lightboard"))
        self.settingsButton.setText(_translate("MainWindow", "Settings"))
        self.instructionButton.setText(_translate("MainWindow", "Instructions"))
        self.label_5.setText(_translate("MainWindow", "Photo 3"))
        self.label_6.setText(_translate("MainWindow", "Photo 4"))
        self.label_7.setText(_translate("MainWindow", "Photo 5"))
        self.label_4.setText(_translate("MainWindow", "Photo 2"))
        self.label_2.setText(_translate("MainWindow", "Photo 1"))
        self.button1.setToolTip(_translate("MainWindow", "Double click to edit the photo name"))
        self.button1.setText(_translate("MainWindow", "-"))
        self.button2.setToolTip(_translate("MainWindow", "Double click to edit the photo name"))
        self.button2.setText(_translate("MainWindow", "-"))
        self.button3.setToolTip(_translate("MainWindow", "Double click to edit the photo name"))
        self.button3.setText(_translate("MainWindow", "-"))
        self.button4.setToolTip(_translate("MainWindow", "Double click to edit the photo name"))
        self.button4.setText(_translate("MainWindow", "-"))
        self.button5.setToolTip(_translate("MainWindow", "Double click to edit the photo name"))
        self.button5.setText(_translate("MainWindow", "-"))

