# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 413)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(391, 413))
        MainWindow.setMaximumSize(QtCore.QSize(391, 413))
        MainWindow.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(0, 185, 255);\n"
"selection-color: rgb(0, 185, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(110, 10, 231, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.path1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.path1.setObjectName("path1")
        self.verticalLayout_2.addWidget(self.path1)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(350, 10, 31, 31))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fileButton1 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.fileButton1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.0340909, x2:1, y2:0, stop:0 rgba(255, 255, 255, 0));\n"
"selection-color: rgb(170, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"Open Sans\";")
        self.fileButton1.setObjectName("fileButton1")
        self.verticalLayout_3.addWidget(self.fileButton1)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(350, 50, 31, 31))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fileButton2 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.fileButton2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.0340909, x2:1, y2:0, stop:0 rgba(255, 255, 255, 0));\n"
"selection-color: rgb(170, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"Open Sans\";")
        self.fileButton2.setObjectName("fileButton2")
        self.verticalLayout_4.addWidget(self.fileButton2)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 50, 91, 31))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(110, 50, 231, 31))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.path2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.path2.setObjectName("path2")
        self.verticalLayout_6.addWidget(self.path2)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(350, 90, 31, 31))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.fileButton3 = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.fileButton3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.0340909, x2:1, y2:0, stop:0 rgba(255, 255, 255, 0));\n"
"selection-color: rgb(170, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"Open Sans\";")
        self.fileButton3.setObjectName("fileButton3")
        self.verticalLayout_7.addWidget(self.fileButton3)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 90, 91, 31))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(110, 90, 231, 31))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.path3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_9)
        self.path3.setObjectName("path3")
        self.verticalLayout_9.addWidget(self.path3)
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(350, 130, 31, 31))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.fileButton4 = QtWidgets.QPushButton(self.verticalLayoutWidget_10)
        self.fileButton4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.0340909, x2:1, y2:0, stop:0 rgba(255, 255, 255, 0));\n"
"selection-color: rgb(170, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"Open Sans\";")
        self.fileButton4.setObjectName("fileButton4")
        self.verticalLayout_10.addWidget(self.fileButton4)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(10, 130, 91, 31))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(110, 130, 231, 31))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.path4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_12)
        self.path4.setObjectName("path4")
        self.verticalLayout_12.addWidget(self.path4)
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(350, 170, 31, 31))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.fileButton5 = QtWidgets.QPushButton(self.verticalLayoutWidget_13)
        self.fileButton5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.0340909, x2:1, y2:0, stop:0 rgba(255, 255, 255, 0));\n"
"selection-color: rgb(170, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"Open Sans\";")
        self.fileButton5.setObjectName("fileButton5")
        self.verticalLayout_13.addWidget(self.fileButton5)
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(10, 170, 91, 31))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_14.addWidget(self.label_5)
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(110, 170, 231, 31))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.path5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.path5.setObjectName("path5")
        self.verticalLayout_15.addWidget(self.path5)
        self.verticalLayoutWidget_16 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(10, 240, 91, 31))
        self.verticalLayoutWidget_16.setObjectName("verticalLayoutWidget_16")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_16)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_16.addWidget(self.label_6)
        self.verticalLayoutWidget_17 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_17.setGeometry(QtCore.QRect(110, 240, 71, 31))
        self.verticalLayoutWidget_17.setObjectName("verticalLayoutWidget_17")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_17)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.key1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_17)
        self.key1.setObjectName("key1")
        self.verticalLayout_17.addWidget(self.key1)
        self.verticalLayoutWidget_18 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(210, 240, 91, 31))
        self.verticalLayoutWidget_18.setObjectName("verticalLayoutWidget_18")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_18)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_18.addWidget(self.label_7)
        self.verticalLayoutWidget_19 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_19.setGeometry(QtCore.QRect(310, 240, 71, 31))
        self.verticalLayoutWidget_19.setObjectName("verticalLayoutWidget_19")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_19)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.key2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_19)
        self.key2.setObjectName("key2")
        self.verticalLayout_19.addWidget(self.key2)
        self.verticalLayoutWidget_20 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_20.setGeometry(QtCore.QRect(10, 280, 91, 31))
        self.verticalLayoutWidget_20.setObjectName("verticalLayoutWidget_20")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_20)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_20)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_20.addWidget(self.label_8)
        self.verticalLayoutWidget_21 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_21.setGeometry(QtCore.QRect(210, 280, 91, 31))
        self.verticalLayoutWidget_21.setObjectName("verticalLayoutWidget_21")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_21)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_21)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_21.addWidget(self.label_9)
        self.verticalLayoutWidget_22 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_22.setGeometry(QtCore.QRect(110, 280, 71, 31))
        self.verticalLayoutWidget_22.setObjectName("verticalLayoutWidget_22")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_22)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.key3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_22)
        self.key3.setObjectName("key3")
        self.verticalLayout_22.addWidget(self.key3)
        self.verticalLayoutWidget_23 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_23.setGeometry(QtCore.QRect(310, 280, 71, 31))
        self.verticalLayoutWidget_23.setObjectName("verticalLayoutWidget_23")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_23)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.key4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_23)
        self.key4.setObjectName("key4")
        self.verticalLayout_23.addWidget(self.key4)
        self.verticalLayoutWidget_24 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_24.setGeometry(QtCore.QRect(110, 320, 71, 31))
        self.verticalLayoutWidget_24.setObjectName("verticalLayoutWidget_24")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_24)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.key5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_24)
        self.key5.setObjectName("key5")
        self.verticalLayout_24.addWidget(self.key5)
        self.verticalLayoutWidget_25 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_25.setGeometry(QtCore.QRect(10, 320, 91, 31))
        self.verticalLayoutWidget_25.setObjectName("verticalLayoutWidget_25")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_25)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_25)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_25.addWidget(self.label_10)
        self.verticalLayoutWidget_31 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_31.setGeometry(QtCore.QRect(80, 360, 111, 41))
        self.verticalLayoutWidget_31.setObjectName("verticalLayoutWidget_31")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_31)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.saveButton = QtWidgets.QPushButton(self.verticalLayoutWidget_31)
        self.saveButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.0340909, x2:1, y2:0, stop:0 rgba(255, 255, 255, 0));\n"
"selection-color: rgb(170, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"Open Sans\";")
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_31.addWidget(self.saveButton)
        self.verticalLayoutWidget_32 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_32.setGeometry(QtCore.QRect(220, 360, 111, 41))
        self.verticalLayoutWidget_32.setObjectName("verticalLayoutWidget_32")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_32)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.clearButton = QtWidgets.QPushButton(self.verticalLayoutWidget_32)
        self.clearButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.0340909, x2:1, y2:0, stop:0 rgba(255, 255, 255, 0));\n"
"selection-color: rgb(170, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"Open Sans\";")
        self.clearButton.setObjectName("clearButton")
        self.verticalLayout_32.addWidget(self.clearButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Settings"))
        self.label.setText(_translate("MainWindow", "Photo 1 path/url"))
        self.fileButton1.setText(_translate("MainWindow", "..."))
        self.fileButton2.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Photo 2 path/url"))
        self.fileButton3.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "Photo 3 path/url"))
        self.fileButton4.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "Photo 4 path/url"))
        self.fileButton5.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "Photo 5 path/url"))
        self.label_6.setText(_translate("MainWindow", "Photo 1 key"))
        self.label_7.setText(_translate("MainWindow", "Photo 2 key"))
        self.label_8.setText(_translate("MainWindow", "Photo 3 key"))
        self.label_9.setText(_translate("MainWindow", "Photo 4 key"))
        self.label_10.setText(_translate("MainWindow", "Photo 5 key"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))

